### ISSUE TITLE
Hcal SP Overlap

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMXAnalysis/ldmx-sw#1109]
**Describe the bug**
@omar-moreno discovered this bug when updating the recoil tracker scoring planes.

It looks like the scoring plane around the back hcal is a little too close to the beam axis and extends into the side hcal volumes.

@EinarElen @cmantill 

https://github.com/LDMX-Software/ldmx-sw/pull/1100#issuecomment-1295677668

![hcal scoring plane vis](https://user-images.githubusercontent.com/3708508/198755582-3a6129c0-176e-4cc2-ae6e-c03ea295709d.png)

**Comment by EinarElen** [comment]
From what I can tell the main issue here for the back hcal isn't actually that the back hcal scoring plane is wrong but that some of the back hcal layers are misaligned. I think we missed this because we were looking at wireframes where this was hard to see, in a solid visualization like below it is more clear. 
![Screenshot from 2022-11-08 08-10-17](https://user-images.githubusercontent.com/14233914/200498176-f3e75496-59d1-4dea-b2a3-f29ad9326330.png)

Regarding the Side Hcal part, I'm less sure about how to approach it since I'm not too familiar with how the scoring planes are used. Either we could surround the back hcal in one set of planes and the side hcal with another or we could surround the entire hcal with one big box.

**Comment by EinarElen** [comment]
@cmantill the offset here (appearing in both X/Y-oriented scintillator layers) seems to be `+ hcal_scintWidth/2.0`.

**Comment by EinarElen** [comment]
For updating the scoring planes, I _think_ the most straight-forward approach would be to replace references to `back_hcal_dfoo` with `hcal_envelope_dfoo` in the scoring planes file, assuming that we just want to make the scoring planes large enough to fit the entire back + side hcal.

**Comment by cmantill** [comment]
I guess that it makes sense to surround the back hcal in one set of scoring planes. For the side hcal we can do a separate box but I guess that in that case we need to be careful with the Ecal scoring planes?

**Comment by cmantill** [comment]
> hcal_scintWidth

Hi @EinarElen , ok great. I think that that should be because we are placing the plate of absorber directly but then the scintillator bars need to be centered at `hcalScintWidth/2.0`. Can you add that to https://github.com/LDMX-Software/ldmx-sw/blob/trunk/Detectors/data/ldmx-det-v14/hcal.gdml#L274 and https://github.com/LDMX-Software/ldmx-sw/blob/trunk/Detectors/data/ldmx-det-v14/hcal.gdml#L285 ?

**Comment by EinarElen** [comment]
Right, I'll make a PR with both of those changes

**Comment by EinarElen** [comment]
Should the change be at those places or in the `back_hcal_startX_scint`/`back_hcal_startY_scint`-variables? I think doing it there would make more sense and as far as I can tell, it doesn't affect anything else
