### ISSUE TITLE
Simplify (re)compilation and use a script instead

### ISSUE THREAD

**Issue by tvami** [LDMXAnalysis/ldmx-sw#1278]
**Is your feature request related to a problem? Please describe.**

Not really a problem but would be nice if we didn't need to run
```
ldmx cmake -B build -S .
ldmx cmake --build build --target install
```
all the time we need to (re)compile.

**Describe the solution you'd like**

```
ldmx ./scripts/ldmx-compile.sh
```
where `ldmx-compile.sh` contains the commands above using `LDMX_BASE`

**Describe alternatives you've considered**

Copy-pasting every time when compilation is needed.

**Comment by EinarElen** [comment]
I've been wanting to add something like this as well for a while. I'd probably be in favour of adding some CLI options if you want to customize e.g. build dirs, number of compile jobs ($(nproc) is probably a good default), etc

I would also consider having a corresponding recompile and run-script since whenever you are working on LDMX-sw, one of the most common things to do is 
cd ../build && build commands && cd ../install && fire ...
