### ISSUE TITLE
Implement Improved BDT

### ISSUE THREAD

**Issue by tomeichlersmith** [LDMXAnalysis/ldmx-sw#1305]
@aechavez developed a better-performing ECal BDT [in python](https://github.com/IncandelaLab/LDMX-scripts/tree/master/pyEcalVeto) and we are looking at implementing it into ldmx-sw so that it can eventually replace the current BDT that is part of the ECal Veto.

This implementation can probably be tied with LDMX-Software/ldmx-sw#1306 which already plans to de-couple the calculation of ECal shower features from the construction of the BDT feature vector and evaluation of the BDT. Since the improved BDT uses a different feature vector than the current BDT (Gabrielle), it will probably be evaluated using a separate processor than Gabrielle (and its predecessors).

## pyEcalVeto
- `treeMaker.py` calculates these variables using some helper functions form `mods/physTools.py`
  - https://github.com/IncandelaLab/LDMX-scripts/blob/2cfc111bd79507d3ce84a3dd571af9282af21254/pyEcalVeto/treeMaker.py#L149 
- x,y,i_layer coordinates
- three segments: front (layers 0-5), mid (6-16), back (17-33) (non-optimized but decent)
- project electron and photon through ecal
  - get electron's momentum from front ecal scoring plane
  - use beam momentum and electron's momentum at target scoring planes to calculate photon's (assuming no other loss)

**Comment by aechavez** [comment]
I will leave some design notes below for anyone who wants to work on this in the future. Please don't hesitate to reach out if questions arise.

## BDT Design

- The improved BDT adds longitudinal segmentation and MIP tracking
- Feature calculation starts by projecting the electron and photon through the ECal
  - Both particles are projected along straight lines
  - The electron trajectory is determined by the recoil electron's position and momentum at the front ECal scoring plane
  - The photon trajectory is inferred from the recoil electron's position and momentum at the furthest downstream target scoring plane and the conservation of momentum
  - One elaboration that can be made here would be to get this data from tracking information instead of the scoring planes

### Longitudinal Segmentation

- The ECal is divided into 3 longitudinal segments:
  - Front segment: Layers 0 - 5
  - Middle segment: Layers 6 - 16
  - Back segment: Layers 17 - 33
  - These values have not been optimized, but seem to work well enough
- The following 8 features are calculated for each segment:
  - Total energy deposited
  - Number of recorded hits
  - Energy-weighted average position of recorded hits (X, Y, Layer#)
  - Energy-weighted standard deviation in position of recorded hits (X, Y, Layer#)

### Radii of Containment

- The radii of containment characterize the shower profile of each trajectory
- They are defined as the radii containing 68% of the shower energy on average
- The values are different for each layer and depend on the detector geometry to some degree
- Just 1 set of radii is used for the photon trajectory, while 4 are used for the electron trajectory
  - Which set is used for the electron trajectory depends on the electron's angle and momentum at the front ECal scoring plane
  - Set 1: theta < 10 deg, p > 500 MeV
  - Set 2: theta < 10 deg, p < 500 MeV
  - Set 3: 10 deg < theta < 20 deg
  - Set 4: theta > 20 deg
- The values for the radii currently used by the BDT were calculated using an old version of ldmx-sw with the v9 detector geometry, so one elaboration that can be made here would be to update these values for use in the current framework
- In each layer, 5 concentric circles are drawn around the electron trajectory, and another 5 are drawn around the photon trajectory
- The radii of these concentric circles are integer multiples (From 1x up to 5x) of the radii of containment for the given layer
- These concentric circles define 5 regions around each trajectory:
  - 1 inner, disk-shaped region
  - 4 annular regions
- There are an additional 5 outer regions defined between the trajectories:
  - 1 region comprising everything outside the trajectories' disk-shaped regions
  - 4 regions comprising everything beyond the trajectories' corresponding annular regions
- Corresponding regions across layers are grouped together, resulting in 15 "volumes" per segment
- The following 8 features are calculated for each volume:
  - Total energy deposited
  - Number of recorded hits
  - Energy-weighted average position of recorded hits (X, Y, Layer#)
  - Energy-weighted standard deviation in position of recorded hits (X, Y, Layer#)

### MIP Tracking

- The following 8 MIP tracking features are also calculated (These features were designed by Juan Lazaro, so my description of them may be less detailed):
  - Number of tracks recorded by Juan's straight4 algorithm
  - Layer# of the first layer with a hit falling within 1 cell of the photon trajectory
  - Number of recorded hits falling within 1 cell of the photon trajectory
  - Number of recorded hits falling within a certain portion of the ECal containing the electron trajectory
  - Number of recorded hits falling within a certain portion of the ECal containing the photon trajectory
  - The ratio of the previous 2 features
  - Separation of the electron and photon trajectories at the ECal face
  - Dot product of the two unit vectors pointing along the electron and photon trajectories

## BDT Feature List

- The description above accounts for a total of 395 features
- To reduce overfitting, I performed a N-1 study based on some simple measures of performance (AUROC, pT-bias plots, and signal efficiencies) to reduce the feature list down to just 47 features

### Core

These core features were carried over from the old BDT model:

1. nReadoutHits: Number of recorded hits in the ECal
2. summedDet: Total energy deposited in the ECal
3. summedTightIso: Total isolated energy in the ECal
4. maxCellDep: Maximum energy deposited in a single cell
5. showerRMS: RMS in XY-position of recorded hits in the ECal
6. xStd: Energy-weighted standard deviation in X-position of recorded hits in the ECal
7. yStd: Energy-weighted standard deviation in Y-position of recorded hits in the ECal
8. avgLayerHit: Energy-weighted average Layer# of recorded hits in the ECal
9. stdLayerHit: Energy-weighted standard deviation in Layer# of recorded hits in the ECal
10. deepestLayerHit: Layer# of the deepest layer with a recorded hit
11. ecalBackEnergy: Total energy deposited in the last several layers of the ECal

### MIP Tracking

12. straight4: Number of tracks recorded by Juan's straight4 algorithm
13. firstNearPhLayer: Layer# of the first layer with a hit falling within 1 cell of the photon trajectory
14. nNearPhHits: Number of recorded hits falling within 1 cell of the photon trajectory
15. photonTerritoryHits: Number of recorded hits falling within a certain portion of the ECal containing the photon trajectory
16. epSep: Separation of the electron and photon trajectories at the ECal face
17. epDot: Dot product of the two unit vectors pointing along the electron and photon trajectories

### Longitudinal Segmentation

18. energy_s1: Total energy deposited in the front segment
19. xMean_s1: Energy-weighted average X-position of recorded hits in the front segment
20. yMean_s1: Energy-weighted average Y-position of recorded hits in the front segment
21. layerMean_s1: Energy-weighted average Layer# of recorded hits in the front segment
22. energy_s2: Total energy deposited in the middle segment
23. yMean_s3: Energy-weighted average Y-position of recorded hits in the back segment

### Radii of Containment (Electron)

24. eContEnergy_x1_s1: Total energy deposited in the first electron volume in the front segment
25. eContEnergy_x2_s1: Total energy deposited in the second electron volume in the front segment
26. eContYMean_x1_s1: Energy-weighted average Y-position of recorded hits in the first electron volume in the front segment
27. eContEnergy_x1_s2: Total energy deposited in the first electron volume in the middle segment
28. eContEnergy_x2_s2: Total energy deposited in the second electron volume in the middle segment
29. eContYMean_x1_s2: Energy-weighted average Y-position of recorded hits in the first electron volume in the middle segment

### Radii of Containment (Photon)

30. gContNHits_x1_s1: Number of recorded hits in the first photon volume in the front segment
31. gContYMean_x1_s1: Energy-weighted average Y-position of recorded hits in the first photon volume in the front segment
32. gContNHits_x1_s2: Number of recorded hits in the first photon volume in the middle segment

### Radii of Containment (Outside)

33. oContEnergy_x1_s1: Total energy deposited in the first outside volume in the front segment
34. oContEnergy_x2_s1: Total energy deposited in the second outside volume in the front segment
35. oContEnergy_x3_s1: Total energy deposited in the third outside volume in the front segment
36. oContNHits_x1_s1: Number of recorded hits in the first outside volume in the front segment
37. oContXMean_x1_s1: Energy-weighted average X-position of recorded hits in the first outside volume in the front segment
38. oContYMean_x1_s1: Energy-weighted average Y-position of recorded hits in the first outside volume in the front segment
39. oContYMean_x2_s1: Energy-weighted average Y-position of recorded hits in the second outside volume in the front segment
40. oContYStd_x1_s1: Energy-weighted standard deviation in Y-position of recorded hits in the first outside volume in the front segment
41. oContEnergy_x1_s2: Total energy deposited in the first outside volume in the middle segment
42. oContEnergy_x2_s2: Total energy deposited in the second outside volume in the middle segment
43. oContEnergy_x3_s2: Total energy deposited in the third outside volume in the middle segment
44. oContLayerMean_x1_s2: Energy-weighted average Layer# of recorded hits in the first outside volume in the middle segment
45. oContLayerStd_x1_s2: Energy-weighted standard deviation in Layer# of recorded hits in the first outside volume in the middle segment
46. oContEnergy_x1_s3: Total energy deposited in the first outside volume in the back segment
47. oContLayerMean_x1_s3: Energy-weighted standard deviation in Layer# of recorded hits in the first outside volume in the back segment
