### ISSUE TITLE
Rewrite ECal geometry in GDML detector description

### ISSUE THREAD

**Issue by JeremyMcCormick** [LDMXAnalysis/ldmx-sw#146]
The current ECal geometry description is not structured very well -- it is essentially using thousands of polyhedral planes, as dumped from the Cal Geant4 runtime.

Instead, each ECal layer can be defined as the union of two trapezoids.  

Each module should have its own logical volume which can be assigned a module number.

The layer structure should be built using GDML loops.

This should make the detector description much easier to read as well as making it more suitable for changes to the layering structure, which are difficult to implement now without dumping GDML from the Calo sim.

**Comment by ocolegro** [comment]
Hi Guys, slides 10 and 11 below contain all relevant information about the longitudinal profile for the current ECAL.

Basically the ECAL starts out with an Si layer and no absorber, followed by a slow ramp in absorber thickness, until a constant thickness of ~1 X0 is reached.

Thick layers are then placed in the very back in order to catch the tail end of E&M fluctuations.

[LDMX_UCSBNewGeom_11_28_2016.pdf](https://github.com/LDMXAnalysis/ldmx-sw/files/920816/LDMX_UCSBNewGeom_11_28_2016.pdf)

**Comment by nhanvtran** [comment]
Here's a first visual look at the two geometries...

old (v2)
[g4_00-v2.pdf](https://github.com/LDMXAnalysis/ldmx-sw/files/1072743/g4_00-v2.pdf)

new (v3)
[g4_01-v3.pdf](https://github.com/LDMXAnalysis/ldmx-sw/files/1072744/g4_01-v3.pdf)

looks reasonable by eye at least.  will try to make some plots now.

**Comment by nhanvtran** [comment]
Here's just sum of energy deposited in the silicon for

old (v2)
![edep-v2](https://user-images.githubusercontent.com/4430387/27102952-b537ce96-504c-11e7-8376-b4f725a5abd7.png)

new (v3)
![edep-v3](https://user-images.githubusercontent.com/4430387/27102953-b542a2bc-504c-11e7-8aaf-6ce7a7d4f910.png)

also looks reasonable

**Comment by JeremyMcCormick** [comment]
Looks good!

Can you generate 10x more statistics easily?

**Comment by nhanvtran** [comment]
10x more stats:

old (v2)
![screen shot 2017-06-13 at 4 17 19 pm](https://user-images.githubusercontent.com/4430387/27105080-dab20f18-5053-11e7-99fd-dd1e281ccaf5.png)

new (v3)
![screen shot 2017-06-13 at 4 16 51 pm](https://user-images.githubusercontent.com/4430387/27105081-dac2d618-5053-11e7-8781-a4c1f5c8c3ca.png)

there are some outliers, not sure why...but it's more consistent than with less stats.

**Comment by nhanvtran** [comment]
@awhitbeck @omar-moreno @JeremyMcCormick 

Ok, so now we can start to see where the difference is... 
Black (v2, old)
Red (v3, new)

energies of each hit
![edep](https://user-images.githubusercontent.com/4430387/27114745-559cd4c4-508b-11e7-8b88-c2dc0ef7e868.png)
energies of each hit, log scale
![edep-log](https://user-images.githubusercontent.com/4430387/27114768-8a87cf86-508b-11e7-85ab-234dabe3b793.png)
energy per hit per event as a function of z position
![edepvz](https://user-images.githubusercontent.com/4430387/27114746-559d3cfc-508b-11e7-8c08-c7ff42a5fb6e.png)
sum energy per event
![sumedep](https://user-images.githubusercontent.com/4430387/27114747-55a03d3a-508b-11e7-9396-18859603c747.png)

**Comment by nhanvtran** [comment]
Ok, I've been staring at this for a while now...the only difference I can find between the 2 geometries is actually in the pre shower...
The V2 geometry has an extra 1mm of Al in the front of it, otherwise, they are identical.  See the text comparison below.  

Now why this translates into a different shower profile is a bit confusing to me (unless I missed something and they are in fact different). 

<img width="637" alt="comp-v3-v2" src="https://user-images.githubusercontent.com/4430387/27572434-92dc85f0-5ad1-11e7-8e3a-d1e2e8a32020.png">

blue is new, black is old
![edepvz](https://user-images.githubusercontent.com/4430387/27572493-f967d248-5ad1-11e7-8ae5-5a75dc960218.png)

**Comment by omar-moreno** [comment]
This issue was resolved by PR 44b98c385ec81d649d2ccb589610b98b6dcc2fdc.
