### ISSUE TITLE
Indent source code within namespace

### ISSUE THREAD

**Issue by JeremyMcCormick** [LDMXAnalysis/ldmx-sw#149]
There should be a 4 space indent within the ldmx namespace.

**Comment by omar-moreno** [comment]
What made you change your mind on this?  You were very adamant about this
... ​

**Comment by JeremyMcCormick** [comment]
It was pointed out to me rather convincingly that it is bad C++ style to not match bracket/indentation scope so I think we should change it.  It is helpful to see that you are in a namespace within classes and functions from the indentation and I think indenting is the standard style.

I wanted to make sure it gets a proper issue as it could potentially make merging in branches quite a pain so I we should discuss about when it would be best to do it.  Probably I would try to do it after the biasing branch gets merged.

**Comment by omar-moreno** [comment]
OK good, I'm glad someone else convinced you because no matter how much I
tried, I couldn't :).

On Jan 30, 2017 16:36, "Jeremy McCormick" <notifications@github.com> wrote:

It was pointed out to me rather convincingly that it is bad C++ style to
not match bracket/indentation scope so I think we should change it. It is
helpful to see that you are in a namespace within classes and functions
from the indentation and I think indenting is the standard style.

I wanted to make sure it gets a proper issue as it could potentially make
merging in branches quite a pain so I we should discuss about when it would
be best to do it. Probably I would try to do it after the biasing branch
gets merged.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/LDMXAnalysis/ldmx-sw/issues/149#issuecomment-276198915>,
or mute the thread
