### ISSUE TITLE
Create v2 detector with larger recoil tracker axial layer and Hcal with 10 mm absorber. 

### ISSUE THREAD

**Issue by omar-moreno** [LDMXAnalysis/ldmx-sw#190]

**Comment by JeremyMcCormick** [comment]
[This commit](https://github.com/LDMXAnalysis/ldmx-sw/commit/252ff334b7729c044baa72ac2fe8b0abb091f631) adds the changes to recoil layer 5.

**Comment by awhitbeck** [comment]
I have changed the hcal absorber from 50mm to 10 mm and tripled the number of layers so that the total interaction length was constant.   Geometry before:

![image](https://cloud.githubusercontent.com/assets/4173436/23344725/8f9dda3c-fc81-11e6-8642-ed7aedc371c1.png)

Geometry after changes:

![image](https://cloud.githubusercontent.com/assets/4173436/23344726/9bac67a8-fc81-11e6-86ba-ac34f79bfaa5.png)

**Comment by omar-moreno** [comment]
This issue is resolved by PR 5d861062ed838b8883ae191a78a8bc603af88145
