### ISSUE TITLE
Get GEANT3 to work with ldmx-sw

### ISSUE THREAD

**Issue by nhanvtran** [LDMXAnalysis/ldmx-sw#239]

**Comment by JeremyMcCormick** [comment]
Not sure this is something that belongs in our issue tracker until we know what we want to accomplish with this and have some actual plan on how to do it.  Otherwise, it is just likely to sit here for months without any action.

Also, if the PN modeling is supposedly better in GEANT3 then I would like to see some evidence from the literature that this is the case before we go down this rabbit hole.

**Comment by omar-moreno** [comment]
Is there evidence in the literature that Geant4 is better? ;)

**Comment by JeremyMcCormick** [comment]
There are no concrete plans to do this and the technical hurdles are non-trivial.  Closing for now.  (Re-open in the unlikely chance you are actually going to work on it!)
